name: GalicoSolutions

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: deploy_environment
      run: |
        echo "${CI_COMMIT_REF_NAME}"        
        tools/deploy-git.sh $CI_COMMIT_REF_NAME
      
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
